name: Deploy to Preview Channel

on:
  push:
    branches:
      - dev

jobs:
 build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: npm ci && npm run build

      - uses: FirebaseExtended/action-hosting-deploy@v0

        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TRY_HOSTING_A5EDA }}
          expires: 30d
          projectId: try-hosting-a5eda
          channelId: preview
